Ristorante.MVC/Controllers/MenuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Ristorante.Core.BusinessLayer;
using Ristorante.Core.Entities;
using Ristorante.MVC.Helper;
using Ristorante.MVC.Models;

namespace Ristorante.MVC.Controllers
{
    public class MenuController : Controller
    {
        private readonly IBusinessLayer BL;

        public MenuController(IBusinessLayer bl)
        {
            this.BL = bl;
        }
        public IActionResult Index()
        {
            List<Menu> menu = BL.GetAllMenu();
            List<MenuViewModel> menuViewModel = new List<MenuViewModel>();
            foreach (var m in menu)
            {
                menuViewModel.Add(m.ToMenuViewModel());
            }
            return View(menuViewModel);
        }

        public IActionResult Details(int id)//passo l'id del menu e voglio tutti i piatti con quel menù
        {
            var piatti = BL.GetAllPiatti().Where(p=>p.MenuId == id);
            List<PiattoViewModel> piattiViewModel = new List<PiattoViewModel>();

            foreach (var p in piatti)
            {
                piattiViewModel.Add(p.ToPiattoViewModel());
            }
            return View(piattiViewModel);
        }


        [Authorize(Policy = "Adm")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Policy = "Adm")]
        [HttpPost]
        public IActionResult Create(MenuViewModel menuViewModel)
        {
            if (ModelState.IsValid)
            {
                Menu menu = menuViewModel.ToMenu();
                Esito esito = BL.AggiungiMenu(menu);
                if (esito.IsOk == true)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.MessaggioErrore = esito.Messaggio;
                    return View("ErroriDiBusiness");
                }
            }
            return View(menuViewModel);
        }

        
    }
}

Ristorante.MVC/Controllers/PiattiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Ristorante.Core.BusinessLayer;
using Ristorante.Core.Entities;
using Ristorante.MVC.Helper;
using Ristorante.MVC.Models;

namespace Ristorante.MVC.Controllers
{
    public class PiattiController : Controller
    {
        private readonly IBusinessLayer BL;

        public PiattiController(IBusinessLayer bl)
        {
            this.BL = bl;
        }
        public IActionResult Index()
        {
            var piatti = BL.GetAllPiatti();
            List<PiattoViewModel> piattiViewModel = new List<PiattoViewModel>();
            foreach (var piatto in piatti)
            {
                piattiViewModel.Add(piatto.ToPiattoViewModel());
            }
            return View(piattiViewModel);
        }

        [Authorize(Policy = "Adm")]
        public IActionResult Create()
        {
            LoadViewBag();
            return View();
        }

        [Authorize(Policy = "Adm")]
        [HttpPost]
        public IActionResult Create(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                Piatto piatto = piattoViewModel.ToPiatto();
                Esito esito = BL.AddPiatto(piatto);
                if (esito.IsOk)
                {

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.MessaggioErrore = esito.Messaggio;
                    return View("ErroriDiBusiness");

                }
                return View(piattoViewModel);
            }
            return View(piattoViewModel);
        }

        [Authorize(Policy = "Adm")]
        public IActionResult Edit(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);
            var piattoViewModel = piatto.ToPiattoViewModel();
            return View(piattoViewModel);
        }

        [Authorize(Policy = "Adm")]
        [HttpPost]
        public IActionResult Edit(PiattoViewModel piattoViewModel)
        {
            if (ModelState.IsValid)
            {
                var piatto = piattoViewModel.ToPiatto();
                Esito esito = BL.UpdatePiatto(piatto.Id, piatto.Nome, piatto.Descrizione, piatto.Tipologia, piatto.Prezzo);
                if (esito.IsOk == true)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.MessaggioErrore = esito.Messaggio;
                    return View("ErroriDiBusiness");
                }
            }
            return View(piattoViewModel);

        }

        [Authorize(Policy = "Adm")]
        public IActionResult Delete(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);
            var piattoViewModel = piatto.ToPiattoViewModel();
            return View(piattoViewModel);

        }

        [Authorize(Policy = "Adm")]
        [HttpPost]
        public IActionResult Delete(PiattoViewModel piattoViewModel)
        {

            var piatto = piattoViewModel.ToPiatto();
            var esito = BL.EliminaPiatto(piatto.Id);
            if (esito.IsOk == true)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.MessaggioErrore = esito.Messaggio;
                return View("ErroriDiBusiness");
            }
        }




        private void LoadViewBag()
        {

            ViewBag.Tipologia = new SelectList(new[]
            {
                new{Value="1", Text="Secondo"},
                new{Value="2", Text="Contorno"},
                new{Value="3", Text="Dolce"}
            }.OrderBy(x => x.Value), "Value", "Text");
        }


        [Authorize(Policy = "Adm")]
        public IActionResult Decouple(int id)
        {
            var piatto = BL.GetAllPiatti().FirstOrDefault(p => p.Id == id);
            var piattoViewModel = piatto.ToPiattoViewModel();
            return View(piattoViewModel);
        }

        [Authorize(Policy = "Adm")]
        [HttpPost]
        public IActionResult Decouple(PiattoViewModel piattoViewModel)
        {

            var piatto = piattoViewModel.ToPiatto();
            Esito esito = BL.TogliPiattoDalMenu(piatto);
            if (esito.IsOk == true)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.MessaggioErrore = esito.Messaggio;
                return View("ErroriDiBusiness");
            }


        }
    }
}

Ristorante.MVC/Controllers/UtentiController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Ristorante.Core.BusinessLayer;
using Ristorante.MVC.Models;
using System.Security.Claims;

namespace Ristorante.MVC.Controllers
{
    public class UtentiController : Controller
    {
        private readonly IBusinessLayer BL;
        public UtentiController(IBusinessLayer bl)
        {
            BL = bl;
        }
        public IActionResult Login(string returnUrl = "/") 
        {

            return View(new UtenteViewModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public async Task<IActionResult> LoginAsync(UtenteViewModel utenteViewModel)
        {
            if (utenteViewModel == null) 
            {
                return View();               
            }

            var utente = BL.GetAccount(utenteViewModel.Username); 

            if (utente != null && ModelState.IsValid)
            {
                
                if (utente.Password == utenteViewModel.Password)
                {                   
                    var claim = new List<Claim>{
                        new Claim(ClaimTypes.Name, utente.Username),
                        new Claim(ClaimTypes.Role, utente.Ruolo.ToString())
                    };
                    
                    var properties = new AuthenticationProperties
                    {
                        RedirectUri = utenteViewModel.ReturnUrl,
                        ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1),
                    };

                    var clainIdentity = new ClaimsIdentity(claim, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync( 
                          CookieAuthenticationDefaults.AuthenticationScheme,
                          new ClaimsPrincipal(clainIdentity),
                          properties);
                    return Redirect("/");
                }

                else
                {
                    ModelState.AddModelError(nameof(utenteViewModel.Password), "Password errata");
                    return View(utenteViewModel);
                }
            }
            else
            {
                return View(utenteViewModel);
            }
            return View();

        }

        
        public IActionResult Forbidden() => View(); 


        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync(); 
            return Redirect("/");

        }
    }
}

Ristorante.MVC/Views/Shared/ErroriDiBusiness.cshtml
<p>@ViewBag.MessaggioErrore</p>

Ristorante.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ristorante.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ristorante.MVC.styles.css" asp-append-version="true" />
</head>
<body>

    @if (User.Identity.IsAuthenticated)
    {
        var name = ((System.Security.Claims.ClaimsIdentity)User.Identity).Claims.FirstOrDefault(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value;

        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Otto Bontà</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contatti">Contatti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Menù</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Piatti" asp-action="Index">Piatti</a>
                            </li>


                        </ul>
                    </div>
                    <a asp-controller="Utenti" asp-action="Logout">Logout</a>
                </div>
            </nav>
        </header>
    }
  
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Ristorante.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>